classDiagram

class GameController{
    startGame()
}

class Maze{
    loadMaze()
}

class Light{
    move()
}

class Mirror{
    reflect()
}

class Goal{
    checkGoal()
}

GameController --> Maze
GameController --> Light
Maze --> Mirror
Maze --> Goal