classDiagram

class GameController{
    +startGame()
}

class Maze{
    +loadMaze()
}

class LightBeam{
    +move()
    +reflect()
}

class Mirror{
    +changeDirection()
}

class Goal{
    +checkGoal()
}

GameController --> Maze
GameController --> LightBeam
Maze --> Mirror
Maze --> Goal